name: 'Deploy the site using built react code'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
        cache: npm
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with: 
        path: 'dist/'
    - name: Deploy Pages
      id: deployment
      uses: actions/deploy-pages@v3
